### ISSUE TITLE
Enable texting and voice transmission only when at least 1 message has been received.

### ISSUE THREAD

**Issue by kerk12** [kerk12/palaemon_passenger_app#4]
As the application must be used only when a real emergency occurs, it has been decided that the user be able to message the crew members only when the crew has messaged them first. As such, we need to enable the texting and voice messaging functionality when `>= 1 messages` exist.

Dependencies: #3, #4

**Comment by sotiriosmoustogiannis** [comment]
I have tried to implement this.  It is functional. 
I have made a merge request, but maybe it is not so good coding.

**Comment by kerk12** [comment]
Congrats @sotiriosmoustogiannis. It's working, however you have done a lot more than what was needed (in terms of coding). Some of your code didn't need to be written at all. Check the merged #17, you will understand why. Thanks for the contribution 🥇
